spring:
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:ORCL
    username: rm551289
    password: 010502
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    show-sql: true
